name: Compile Check

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    name: Build (iOS Simulator)
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Show project info
        run: |
          ls mini-me/
          xcodebuild -project mini-me/mini-me.xcodeproj -list

      - name: Build mini-me + widget
        run: |
          xcodebuild \
            -project mini-me/mini-me.xcodeproj \
            -scheme mini-me \
            -destination "generic/platform=iOS Simulator" \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            ASSETCATALOG_COMPILER_SKIP_APP_STORE_DEPLOYMENT=YES \
            build 2>&1
